let num1: number = 8;
let num2: number = 3;
let num3: number;
let num4: string = "10";
let num5: boolean = true;
num3 = num1 + num2;
console.log(num1, "+", num2, "=", num3);
num3 = num1 - num2;
console.log(num1, "-", num2, "=", num3);
num3 = num1 * num2;
console.log(num1, "*", num2, "=", num3);
num3 = num1 / num2;
console.log(num1, "/", num2, "=", num3);
console.log(num4, "+", num5, "=", num4 + num5);
